modLoader = "javafml"
loaderVersion = "[${forge},)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/rhysdh540/infiniclouds/issues"

[[mods]]
modId = "infiniclouds"
version = "${version}"
displayName = "Infiniclouds"
logoFile = "icon.png"
authors = "rdh"
description = '''
Makes clouds render farther out.
'''

[[dependencies.infiniclouds]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infiniclouds]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "BOTH"
